# Generated by Django 3.2.25 on 2026-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('textarea', models.TextField(max_length=500)),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
    ]
