# Generated by Django 3.2.25 on 2026-01-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknames',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
